from __future__ import annotations

import re
from dataclasses import dataclass
from string import Formatter

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.lot import LotTemplate


LOT_TEMPLATE_FIELDS = frozenset(
    {
        "plan",
        "duration",
        "duration_minutes",
        # Deprecated compatibility field for operator-edited day templates.
        "days",
        "condition",
        "long_window_days",
        "min_limit",
        "short_limit",
        "long_limit",
    }
)
REQUIRED_LOT_TITLE_FIELDS = frozenset({"plan", "condition"})
LOT_TEMPLATE_KEY_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{1,63}$")

# Upper bounds of values generated by the catalog/reconciler.  Saving a
# template against these values guarantees that a later substitution cannot
# turn an API-valid source into an overlong FunPay payload.  Runtime checks are
# kept as defence in depth for legacy rows and direct database edits.
_MAX_RENDER_VALUES: dict[str, str] = {
    "plan": "P" * 120,
    "duration": "30 days 23 hours 30 minutes",
    "duration_minutes": "43200",
    "days": "9" * 10,
    "condition": "C" * 64,
    "long_window_days": "99",
    "min_limit": "100%",
    "short_limit": "100%",
    "long_limit": "100%",
}


@dataclass(frozen=True)
class DefaultLotTemplate:
    key: str
    name: str
    title_ru: str
    title_en: str
    description_ru: str
    description_en: str


LEGACY_DAY_LOT_TEMPLATES: dict[str, DefaultLotTemplate] = {
    "default": DefaultLotTemplate(
        key="default",
        name="Основной шаблон лота",
        title_ru="ChatGPT {plan} — {days} дн. — {condition}",
        title_en="ChatGPT {plan} — {days} days — {condition}",
        description_ru=(
            "Доступ к аккаунту ChatGPT {plan} на {days} дн.\n"
            "Условие выдачи: {condition}.\n"
            "Длительное окно Codex: {long_window_days} дн. (30 дней только на "
            "Free, 7 дней на платных тарифах). Перед выдачей бот "
            "проверяет фактический остаток OpenAI.\n"
            "Данные приходят в чат FunPay. Код входа: !код, помощь: !помощь."
        ),
        description_en=(
            "ChatGPT {plan} account access for {days} days.\n"
            "Delivery condition: {condition}.\n"
            "Long Codex window: {long_window_days} days (30 days on Free only, "
            "7 days on paid plans). Before delivery, the "
            "bot checks the actual OpenAI allowance.\n"
            "Credentials arrive in FunPay chat. Login code: !code, help: !help."
        ),
    )
}

PRE_PREMIUM_LOT_TEMPLATES: dict[str, DefaultLotTemplate] = {
    "default": DefaultLotTemplate(
        key="default",
        name="Основной шаблон лота",
        title_ru="ChatGPT {plan} — {duration} — {condition}",
        title_en="ChatGPT {plan} — {duration} — {condition}",
        description_ru=(
            "Доступ к аккаунту ChatGPT {plan} на {duration}.\n"
            "Условие выдачи: {condition}.\n"
            "Длительное окно Codex: {long_window_days} дн. (30 дней только на "
            "Free, 7 дней на платных тарифах). Перед выдачей бот "
            "проверяет фактический остаток OpenAI.\n"
            "Данные приходят в чат FunPay. Код входа: !код, помощь: !помощь."
        ),
        description_en=(
            "ChatGPT {plan} account access for {duration}.\n"
            "Delivery condition: {condition}.\n"
            "Long Codex window: {long_window_days} days (30 days on Free only, "
            "7 days on paid plans). Before delivery, the "
            "bot checks the actual OpenAI allowance.\n"
            "Credentials arrive in FunPay chat. Login code: !code, help: !help."
        ),
    )
}


PRE_REFINED_LOT_TEMPLATES: dict[str, DefaultLotTemplate] = {
    "default": DefaultLotTemplate(
        key="default",
        name="Основной шаблон лота",
        title_ru="ChatGPT {plan} · {duration} · {condition}",
        title_en="ChatGPT {plan} · {duration} · {condition}",
        description_ru=(
            "Доступ к аккаунту ChatGPT {plan} на {duration}.\n"
            "Условие выдачи: {condition}.\n\n"
            "Лимит Codex\n"
            "Длительное окно: {long_window_days} дн. — 30 дней только на "
            "Free, 7 дней на платных тарифах. Перед выдачей бот сверяет "
            "последнюю успешную проверку остатка лимита Codex.\n\n"
            "Данные для входа придут в чат FunPay. Код для входа: !код. "
            "Помощь: !помощь."
        ),
        description_en=(
            "Access to a ChatGPT {plan} account for {duration}.\n"
            "Delivery terms: {condition}.\n\n"
            "Codex allowance\n"
            "Long window: {long_window_days} days — 30 days for Free and "
            "7 days for paid plans. Before delivery, the bot checks the latest "
            "successful Codex allowance reading.\n\n"
            "Sign-in details will arrive in FunPay chat. Sign-in code: !code. "
            "Help: !help."
        ),
    )
}


DEFAULT_LOT_TEMPLATES: dict[str, DefaultLotTemplate] = {
    "default": DefaultLotTemplate(
        key="default",
        name="Основной шаблон лота",
        title_ru="🧊 ChatGPT {plan} · {duration} · {condition} · АВТОВЫДАЧА",
        title_en="🧊 ChatGPT {plan} · {duration} · {condition} · AUTO DELIVERY",
        description_ru=(
            "🧊━━━━━━━━━━━━━━━━━━━━🧊\n"
            "🛰️ ДОСТУП К CHATGPT {plan}\n"
            "🧊━━━━━━━━━━━━━━━━━━━━🧊\n\n"
            "🔹 СРОК И УСЛОВИЯ\n"
            "• Доступ: {duration}\n"
            "• Выдача: {condition}\n"
            "• Формат: автоматическая выдача в чате FunPay\n\n"
            "📊 ЛИМИТ CODEX\n"
            "• Проверяемое окно: {long_window_days} дн.\n"
            "• 30 дней только на Free, 7 дней на платных тарифах.\n"
            "• Перед выдачей бот проверяет актуальный остаток лимита.\n\n"
            "🛡️ ПРАВИЛА ДОСТУПА\n"
            "• Не меняйте пароль и настройки безопасности.\n"
            "• Не завершайте чужие сеансы и не удаляйте чужие данные.\n"
            "• При проблеме сначала используйте !помощь, затем !замена.\n\n"
            "🔑 КОМАНДЫ\n"
            "• !код — коды для входа\n"
            "• !подписка — срок доступа и лимит Codex\n"
            "• !помощь — инструкция\n"
            "• !продавец — связь с продавцом"
        ),
        description_en=(
            "🧊━━━━━━━━━━━━━━━━━━━━🧊\n"
            "🛰️ CHATGPT {plan} ACCESS\n"
            "🧊━━━━━━━━━━━━━━━━━━━━🧊\n\n"
            "🔹 PERIOD AND TERMS\n"
            "• Access: {duration}\n"
            "• Delivery: {condition}\n"
            "• Format: automatic delivery in FunPay chat\n\n"
            "📊 CODEX ALLOWANCE\n"
            "• Verified window: {long_window_days} days\n"
            "• Free — 30 days; paid plans — 7 days.\n"
            "• The bot checks the current allowance before delivery.\n\n"
            "🛡️ ACCESS RULES\n"
            "• Do not change the password or security settings.\n"
            "• Do not end other sessions or delete other users' data.\n"
            "• If there is a problem, use !help first, then !replace.\n\n"
            "🔑 COMMANDS\n"
            "• !code — sign-in codes\n"
            "• !sub — access time and Codex allowance\n"
            "• !help — instructions\n"
            "• !seller — contact the seller"
        ),
    )
}

_FORMATTER = Formatter()


class LotTemplateValidationError(ValueError):
    """A lot template is malformed or contains an unsafe placeholder."""


class LotTemplateRenderError(ValueError):
    """A validated lot template cannot be rendered safely for FunPay."""


def validate_lot_template_key(key: str) -> str:
    normalized = key.strip().lower()
    if not LOT_TEMPLATE_KEY_PATTERN.fullmatch(normalized):
        raise LotTemplateValidationError(
            "Template key must be 2-64 lowercase letters, digits, '_' or '-'"
        )
    return normalized


def validate_lot_template_content(
    content: str,
    *,
    field: str,
) -> frozenset[str]:
    """Validate flat ``str.format`` placeholders used by lot publications."""
    try:
        parts = list(_FORMATTER.parse(content))
    except ValueError as exc:
        raise LotTemplateValidationError(
            f"Invalid placeholder syntax in {field}: {exc}"
        ) from exc

    used: set[str] = set()
    for _literal, field_name, format_spec, conversion in parts:
        if field_name is None:
            continue
        if not field_name or field_name not in LOT_TEMPLATE_FIELDS:
            allowed = ", ".join(
                f"{{{name}}}" for name in sorted(LOT_TEMPLATE_FIELDS)
            )
            raise LotTemplateValidationError(
                f"Unknown placeholder {{{field_name or ''}}} in {field}. "
                f"Allowed: {allowed}"
            )
        if conversion or format_spec:
            raise LotTemplateValidationError(
                f"Conversions and format specifications are not allowed in {field}"
            )
        used.add(field_name)

    if field.startswith("title_"):
        missing = REQUIRED_LOT_TITLE_FIELDS.difference(used)
        if missing:
            required = ", ".join(f"{{{name}}}" for name in sorted(missing))
            raise LotTemplateValidationError(
                f"{field} must include {required} so FunPay lots stay identifiable"
            )
        if "duration" not in used and "days" not in used:
            raise LotTemplateValidationError(
                f"{field} must include {{duration}} (or deprecated {{days}}) "
                "so FunPay lots stay identifiable"
            )
    return frozenset(used)


def validate_lot_template_values(
    *,
    title_ru: str,
    title_en: str,
    description_ru: str,
    description_en: str,
) -> None:
    for field, content in (
        ("title_ru", title_ru),
        ("title_en", title_en),
        ("description_ru", description_ru),
        ("description_en", description_en),
    ):
        validate_lot_template_content(content, field=field)
        rendered = content.format_map(_MAX_RENDER_VALUES)
        limit = 255 if field.startswith("title_") else 4_000
        if len(rendered) > limit:
            raise LotTemplateValidationError(
                f"{field} can exceed the FunPay limit of {limit} characters "
                "after variable substitution"
            )


async def resolve_lot_template(
    session: AsyncSession,
    *,
    tier_id: int,
    limit_scope_id: int,
) -> LotTemplate | None:
    """Resolve the most specific enabled override, then the system default."""
    rows = list(
        (
            await session.execute(
                select(LotTemplate).where(LotTemplate.is_enabled.is_(True))
            )
        ).scalars()
    )
    candidates = [
        row
        for row in rows
        if row.tier_id in (None, tier_id)
        and row.limit_scope_id in (None, limit_scope_id)
    ]
    if not candidates:
        return None

    # A targeted template beats a general one. At equal specificity an
    # operator-created override beats the bundled system default. The stable
    # id tie-breaker makes resolution deterministic even for legacy data.
    return max(
        candidates,
        key=lambda row: (
            int(row.tier_id is not None) + int(row.limit_scope_id is not None),
            int(row.tier_id is not None),
            int(not row.system_managed),
            -row.id,
        ),
    )


def render_lot_template(
    template: LotTemplate | None,
    *,
    lang: str,
    variables: dict[str, object],
) -> tuple[str, str]:
    """Render localized title and description with a safe bundled fallback."""
    default = DEFAULT_LOT_TEMPLATES["default"]
    if lang == "en":
        title = template.title_template_en if template else default.title_en
        description = (
            template.description_template_en if template else default.description_en
        )
        title_field = "title_en"
        description_field = "description_en"
    else:
        title = template.title_template_ru if template else default.title_ru
        description = (
            template.description_template_ru if template else default.description_ru
        )
        title_field = "title_ru"
        description_field = "description_ru"

    title_fields = validate_lot_template_content(title, field=title_field)
    description_fields = validate_lot_template_content(
        description, field=description_field
    )
    missing = (title_fields | description_fields).difference(variables)
    if missing:
        display = ", ".join(f"{{{name}}}" for name in sorted(missing))
        raise LotTemplateRenderError(f"Missing lot template variables: {display}")

    rendered_title = title.format_map(variables)
    rendered_description = description.format_map(variables)
    if len(rendered_title) > 255:
        raise LotTemplateRenderError("Rendered FunPay title exceeds 255 characters")
    if len(rendered_description) > 4_000:
        raise LotTemplateRenderError(
            "Rendered FunPay description exceeds 4000 characters"
        )
    return rendered_title, rendered_description
