[CmdletBinding()]
param(
    [string]$PairingUrl,
    [string]$PairingCode,
    [string]$DisplayName = $env:COMPUTERNAME,
    [switch]$EnableAutoStart,
    [switch]$DisableAutoStart,
    [switch]$CreateDesktopShortcuts,
    [string]$InstallRoot = ""
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

# Validate the source directory before importing even Common.ps1.  The
# generated administrative command extracts this package below an atomically
# ACL-protected ProgramData staging directory.  A manually extracted,
# user-writable copy must never become high-integrity code.
$bootstrapPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$bootstrapAdministrator = $bootstrapPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($bootstrapAdministrator) {
    if ($PSVersionTable.PSEdition -ne "Desktop") {
        throw "Administrator setup must run in Windows PowerShell 5.1. Use the command generated by the admin panel."
    }
    $sourceWriteMask = (
        [Security.AccessControl.FileSystemRights]::Write -bor
        [Security.AccessControl.FileSystemRights]::Delete -bor
        [Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles -bor
        [Security.AccessControl.FileSystemRights]::ChangePermissions -bor
        [Security.AccessControl.FileSystemRights]::TakeOwnership
    )
    function Assert-SetupBootstrapPath {
        param([string]$Path, [switch]$Directory)
        $sourceItem = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
        if (($sourceItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -or ($Directory -and -not $sourceItem.PSIsContainer)) {
            throw "Administrator setup source contains an unsafe path. Use the command generated by the admin panel."
        }
        $sourceAcl = Get-Acl -LiteralPath $Path
        $sourceOwner = (New-Object Security.Principal.NTAccount($sourceAcl.Owner)).Translate([Security.Principal.SecurityIdentifier]).Value
        if ($sourceOwner -notin @("S-1-5-18", "S-1-5-32-544")) {
            throw "Administrator setup source is owned by an untrusted principal. Use the command generated by the admin panel."
        }
        foreach ($sourceRule in $sourceAcl.Access) {
            if ($sourceRule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow) { continue }
            $sourceSid = $sourceRule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value
            if ($sourceSid -notin @("S-1-5-18", "S-1-5-32-544") -and ($sourceRule.FileSystemRights -band $sourceWriteMask)) {
                throw "Administrator setup source is writable by an untrusted principal. Use the command generated by the admin panel."
            }
        }
    }
    $commonData = [Environment]::GetFolderPath([Environment+SpecialFolder]::CommonApplicationData)
    $stageRoot = Split-Path -Parent $PSScriptRoot
    if (
        -not [IO.Path]::GetFullPath((Split-Path -Parent $stageRoot)).TrimEnd('\').Equals([IO.Path]::GetFullPath($commonData).TrimEnd('\'), [StringComparison]::OrdinalIgnoreCase) -or
        (Split-Path -Leaf $stageRoot) -notmatch '^FunPayHomeRelay-Staging-[a-f0-9]{32}$'
    ) {
        throw "Administrator setup must run only from the protected staging directory generated by the admin panel."
    }
    $commonDataItem = Get-Item -LiteralPath $commonData -Force -ErrorAction Stop
    if (-not $commonDataItem.PSIsContainer -or ($commonDataItem.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw "CommonApplicationData is unsafe." }
    $commonDataAcl = Get-Acl -LiteralPath $commonData
    try {
        $commonDataOwner = (New-Object Security.Principal.NTAccount($commonDataAcl.Owner)).Translate([Security.Principal.SecurityIdentifier]).Value
    } catch {
        throw "CommonApplicationData has an unresolvable owner."
    }
    if ($commonDataOwner -notin @("S-1-5-18", "S-1-5-32-544")) {
        throw "CommonApplicationData is not owned by SYSTEM or Administrators."
    }
    foreach ($sourceRule in $commonDataAcl.Access) {
        if ($sourceRule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow -or ($sourceRule.PropagationFlags -band [Security.AccessControl.PropagationFlags]::InheritOnly)) { continue }
        $sourceSid = $sourceRule.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value
        if ($sourceSid -notin @("S-1-5-18", "S-1-5-32-544") -and ($sourceRule.FileSystemRights -band [Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles)) { throw "CommonApplicationData allows an untrusted principal to replace setup staging." }
    }
    Assert-SetupBootstrapPath -Path $stageRoot -Directory
    Assert-SetupBootstrapPath -Path $PSScriptRoot -Directory
    Assert-SetupBootstrapPath -Path $PSCommandPath
    Assert-SetupBootstrapPath -Path (Join-Path $PSScriptRoot "Common.ps1")
    # Prevent user-profile module shadowing of Expand-Archive, ScheduledTasks,
    # and DISM cmdlets in the high-integrity process.
    $trustedWindowsRoot = [IO.Directory]::GetParent([Environment]::SystemDirectory).FullName
    $env:PSModulePath = Join-Path $trustedWindowsRoot "System32\WindowsPowerShell\v1.0\Modules"
}
. (Join-Path $PSScriptRoot "Common.ps1")

function Install-RelayOpenSshIfNeeded {
    $openSshRoot = Join-Path (Get-RelayWindowsPath) "System32\OpenSSH"
    if (
        (Test-Path -LiteralPath (Join-Path $openSshRoot "ssh.exe") -PathType Leaf) -and
        (Test-Path -LiteralPath (Join-Path $openSshRoot "ssh-keygen.exe") -PathType Leaf)
    ) {
        return
    }

    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "OpenSSH Client is missing. Run this installer once as Administrator so the built-in Windows capability can be enabled."
    }
    $capability = Get-WindowsCapability -Online -Name "OpenSSH.Client~~~~0.0.1.0" -ErrorAction Stop
    if ($capability.State -ne "Installed") {
        Write-Host "Installing the built-in Windows OpenSSH Client..."
        Add-WindowsCapability -Online -Name "OpenSSH.Client~~~~0.0.1.0" | Out-Null
    }
}

function Copy-RelayRuntimeFiles {
    param([Parameter(Mandatory = $true)][string]$Destination)

    $runtimeFiles = @("Common.ps1", "Relay.ps1", "Start.ps1", "Stop.ps1", "Status.ps1", "Uninstall.ps1", "README.md")
    foreach ($name in $runtimeFiles) {
        $source = Join-Path $PSScriptRoot $name
        $target = Join-Path $Destination $name
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
            throw "Setup package is incomplete: $name is missing."
        }
        if ([IO.Path]::GetFullPath($source) -ne [IO.Path]::GetFullPath($target)) {
            Copy-Item -LiteralPath $source -Destination $target -Force
        }
    }
    Set-Content -LiteralPath (Join-Path $Destination "ssh_config") -Value "# Intentionally empty: every SSH option is supplied by Relay.ps1." -Encoding ASCII
}

function Register-RelayAutoStart {
    param([Parameter(Mandatory = $true)][string]$Root)

    if (-not (Test-RelaySystemInstallRoot -Path $Root)) {
        throw "Autostart may reference only the protected ProgramData installation."
    }
    Assert-RelayProtectedSystemRuntime -Root $Root
    $powerShellPath = Get-RelayPowerShellPath
    $relayPath = Join-Path $Root "Relay.ps1"
    $arguments = '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{0}" -InstallRoot "{1}"' -f $relayPath, $Root
    $action = ScheduledTasks\New-ScheduledTaskAction -Execute $powerShellPath -Argument $arguments
    $trigger = ScheduledTasks\New-ScheduledTaskTrigger -AtStartup
    $principal = ScheduledTasks\New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings = ScheduledTasks\New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 999 `
        -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -MultipleInstances IgnoreNew
    ScheduledTasks\Register-ScheduledTask -TaskName $script:RelayTaskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Keeps the restricted FunPay home egress relay connected." -Force | Out-Null
}

function Remove-RelayAutoStart {
    $task = ScheduledTasks\Get-ScheduledTask -TaskName $script:RelayTaskName -ErrorAction SilentlyContinue
    if ($task) {
        if ($task.State -eq "Running") {
            ScheduledTasks\Stop-ScheduledTask -TaskName $script:RelayTaskName -ErrorAction SilentlyContinue
        }
        ScheduledTasks\Unregister-ScheduledTask -TaskName $script:RelayTaskName -Confirm:$false
    }
}

function New-RelayShortcut {
    param(
        [Parameter(Mandatory = $true)][string]$ShortcutPath,
        [Parameter(Mandatory = $true)][string]$ScriptPath,
        [Parameter(Mandatory = $true)][string]$Root
    )

    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($ShortcutPath)
    $shortcut.TargetPath = Get-RelayPowerShellPath
    $keepOpen = if ([IO.Path]::GetFileName($ScriptPath) -eq "Status.ps1") { " -KeepOpen" } else { "" }
    $shortcut.Arguments = '-NoLogo -NoProfile -ExecutionPolicy Bypass -File "{0}" -InstallRoot "{1}"{2}' -f $ScriptPath, $Root, $keepOpen
    $shortcut.WorkingDirectory = $Root
    $shortcut.Description = [IO.Path]::GetFileNameWithoutExtension($ScriptPath) + " FunPay Home Relay"
    $shortcut.Save()
}

function Install-RelayShortcuts {
    param(
        [Parameter(Mandatory = $true)][string]$Root,
        [switch]$SystemInstall,
        [switch]$Desktop
    )

    if ($SystemInstall) {
        Write-Host "Boot mode keeps control scripts in the protected ProgramData directory; no elevated writes are made to user-writable Start Menu or Desktop paths."
        return
    }

    $programs = [Environment]::GetFolderPath("Programs")
    $startMenuFolder = Join-Path $programs "FunPay Home Relay"
    New-Item -ItemType Directory -Path $startMenuFolder -Force | Out-Null
    foreach ($action in @("Start", "Stop", "Status")) {
        New-RelayShortcut -ShortcutPath (Join-Path $startMenuFolder ("{0}.lnk" -f $action)) -ScriptPath (Join-Path $Root ("{0}.ps1" -f $action)) -Root $Root
    }

    if ($Desktop) {
        $desktopPath = [Environment]::GetFolderPath("Desktop")
        foreach ($action in @("Start", "Stop", "Status")) {
            New-RelayShortcut -ShortcutPath (Join-Path $desktopPath ("FunPay Relay - {0}.lnk" -f $action)) -ScriptPath (Join-Path $Root ("{0}.ps1" -f $action)) -Root $Root
        }
    }
}

function Get-PlainPairingCode {
    param([string]$Code)

    if ($Code) {
        return $Code
    }
    $secure = Read-Host "Enter the one-time pairing code from the admin panel" -AsSecureString
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

function Get-RequiredRelayProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if ($Object.PSObject.Properties.Name -notcontains $Name) {
        throw "Pairing response is missing '$Name'."
    }
    $Object.$Name
}

function Invoke-RelayPairing {
    param(
        [Parameter(Mandatory = $true)][string]$Url,
        [Parameter(Mandatory = $true)][string]$Code,
        [Parameter(Mandatory = $true)][string]$PublicKey,
        [Parameter(Mandatory = $true)][string]$Name
    )

    $uri = [Uri]$Url
    if ($uri.Scheme -ne "https") {
        throw "PairingUrl must use HTTPS."
    }
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $body = [ordered]@{
        schema_version = 1
        machine_name = $env:COMPUTERNAME
        display_name = $Name
        public_key = $PublicKey
        client_version = "1.0.0"
    } | ConvertTo-Json

    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers @{ Authorization = "Bearer $Code" } -ContentType "application/json" -Body $body -TimeoutSec 30
    } catch {
        throw "Pairing failed. Generate a new one-time code and retry. Server response was not logged. $($_.Exception.Message)"
    }
}

function Get-RelayPublicKeyFromIdentity {
    param([Parameter(Mandatory = $true)][string]$IdentityPath)

    $publicKeyPath = "$IdentityPath.pub"
    if (-not (Test-Path -LiteralPath $IdentityPath -PathType Leaf)) {
        throw "The existing relay identity is missing or is not a regular file."
    }
    foreach ($path in @($IdentityPath, $publicKeyPath)) {
        if (-not (Test-Path -LiteralPath $path)) { continue }
        $item = Get-Item -LiteralPath $path -Force -ErrorAction Stop
        if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw "The existing relay identity contains an unsafe path. Remove it after inspection and retry."
        }
    }

    # Derive the public key from the private key on every reuse.  Merely
    # trusting a leftover .pub file could register a different key after an
    # interrupted or tampered partial installation.
    $keygenPath = Get-RelaySshKeygenPath
    $derivedPublicKey = ((& $keygenPath -y -f $IdentityPath 2>$null) | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or $derivedPublicKey -notmatch '^ssh-ed25519\s+[A-Za-z0-9+/]+={0,3}(?:\s+[^\r\n]{0,128})?$') {
        throw "The existing relay identity does not contain a valid Ed25519 public key."
    }
    $derivedParts = $derivedPublicKey -split '\s+'

    if (Test-Path -LiteralPath $publicKeyPath -PathType Leaf) {
        $storedPublicKey = (Get-Content -LiteralPath $publicKeyPath -Raw).Trim()
        if ($storedPublicKey -notmatch '^ssh-ed25519\s+[A-Za-z0-9+/]+={0,3}(?:\s+[^\r\n]{0,128})?$') {
            throw "The existing relay public key is damaged. Remove the partial installation after inspection and retry."
        }
        $storedParts = $storedPublicKey -split '\s+'
        if ($storedParts[0] -ne $derivedParts[0] -or $storedParts[1] -ne $derivedParts[1]) {
            throw "The existing relay public key does not match its private key. Refusing to overwrite either file."
        }
    } elseif (Test-Path -LiteralPath $publicKeyPath) {
        throw "The existing relay public-key path is not a regular file."
    } else {
        Set-Content -LiteralPath $publicKeyPath -Value $derivedPublicKey -Encoding ASCII
    }

    $derivedPublicKey
}

function Protect-RelayIdentityFiles {
    param(
        [Parameter(Mandatory = $true)][string]$IdentityPath,
        [switch]$SystemInstall
    )

    Protect-RelayPrivateKey -Path $IdentityPath -SystemInstall:$SystemInstall
    $publicKeyPath = "$IdentityPath.pub"
    if (Test-Path -LiteralPath $publicKeyPath -PathType Leaf) {
        Protect-RelayFile -Path $publicKeyPath -SystemInstall:$SystemInstall
    } elseif (Test-Path -LiteralPath $publicKeyPath) {
        throw "The relay public-key path is not a regular file."
    }
}

function Repair-RelaySystemPublicKeyProtection {
    param([Parameter(Mandatory = $true)][string]$Root)

    Assert-RelayProtectedSystemDirectory -Path $Root
    $identityPath = Join-Path $Root "relay_ed25519"
    $publicKeyPath = "$identityPath.pub"
    if (-not (Test-Path -LiteralPath $publicKeyPath)) {
        return
    }

    $publicKeyItem = Get-Item -LiteralPath $publicKeyPath -Force -ErrorAction Stop
    if ($publicKeyItem.PSIsContainer -or ($publicKeyItem.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "The relay public-key path is unsafe. Remove the partial installation after inspection and retry."
    }

    # Every path except the known ssh-keygen-created public half must already
    # be protected. Users have no create/delete rights on the parent, and the
    # public half is never executed. After revoking its original owner, derive
    # it again from the protected private key to close the recovery race.
    $publicKeyFullPath = [IO.Path]::GetFullPath($publicKeyPath)
    $pending = New-Object 'System.Collections.Generic.Queue[string]'
    $pending.Enqueue([IO.Path]::GetFullPath($Root))
    while ($pending.Count -gt 0) {
        $directory = $pending.Dequeue()
        foreach ($child in Get-ChildItem -LiteralPath $directory -Force -ErrorAction Stop) {
            if (-not [IO.Path]::GetFullPath($child.FullName).Equals($publicKeyFullPath, [StringComparison]::OrdinalIgnoreCase)) {
                Assert-RelayProtectedPath -Path $child.FullName
            }
            if ($child.PSIsContainer) {
                $pending.Enqueue($child.FullName)
            }
        }
    }
    if (-not (Test-Path -LiteralPath $identityPath -PathType Leaf)) {
        throw "A relay public key exists without its private key. Refusing to repair the partial installation."
    }
    Assert-RelayProtectedPath -Path $identityPath
    Protect-RelayFile -Path $publicKeyPath -SystemInstall
    Assert-RelayProtectedPath -Path $publicKeyPath
    [void](Get-RelayPublicKeyFromIdentity -IdentityPath $identityPath)
}

function Get-OrCreateRelayIdentity {
    param(
        [Parameter(Mandatory = $true)][string]$Root,
        [Parameter(Mandatory = $true)][string]$IdentityPath,
        [switch]$SystemInstall
    )

    if (-not (Test-RelayPathInsideRoot -Path $IdentityPath -InstallRoot $Root)) {
        throw "Relay identity path escapes the installation directory."
    }
    $publicKeyPath = "$IdentityPath.pub"
    $identityExists = Test-Path -LiteralPath $IdentityPath
    $publicKeyExists = Test-Path -LiteralPath $publicKeyPath

    if ($identityExists -or $publicKeyExists) {
        if (-not $identityExists) {
            throw "A relay public key exists without its private key. Refusing to overwrite the partial installation."
        }
        Protect-RelayIdentityFiles -IdentityPath $IdentityPath -SystemInstall:$SystemInstall
        $publicKey = Get-RelayPublicKeyFromIdentity -IdentityPath $IdentityPath
        # Get-RelayPublicKeyFromIdentity restores a missing public half from the
        # protected private key. Protect that newly created file before return.
        Protect-RelayIdentityFiles -IdentityPath $IdentityPath -SystemInstall:$SystemInstall
        return $publicKey
    }

    $keygenPath = Get-RelaySshKeygenPath
    $generationRoot = $null
    $generationIdentityPath = $IdentityPath
    try {
        if ($SystemInstall) {
            if ($PSVersionTable.PSEdition -ne "Desktop") {
                throw "Protected identity generation requires Windows PowerShell 5.1."
            }
            Assert-RelayProtectedDirectory -Path $PSScriptRoot
            $generationAcl = New-Object Security.AccessControl.DirectorySecurity
            $generationAcl.SetSecurityDescriptorSddlForm('O:BAG:BAD:P(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)')
            $generationRoot = Join-Path $PSScriptRoot ("RelayIdentity-{0}" -f [Guid]::NewGuid().ToString("N"))
            [void][IO.Directory]::CreateDirectory($generationRoot, $generationAcl)
            Assert-RelayProtectedDirectory -Path $generationRoot
            $generationIdentityPath = Join-Path $generationRoot "relay_ed25519"
        }

        $keyComment = "funpay-home-relay:{0}:{1}" -f $env:COMPUTERNAME, ([Guid]::NewGuid().ToString("N"))
        $keygenArguments = @("-q", "-t", "ed25519", "-a", "64", "-N", "", "-C", $keyComment, "-f", $generationIdentityPath)
        $keygenArgumentLine = (($keygenArguments | ForEach-Object {
            Quote-RelayProcessArgument -Value ([string]$_
            )
        }) -join " ")
        $keygenProcess = Start-Process -FilePath $keygenPath -ArgumentList $keygenArgumentLine -Wait -PassThru -WindowStyle Hidden
        if ($keygenProcess.ExitCode -ne 0 -or -not (Test-Path -LiteralPath $generationIdentityPath -PathType Leaf)) {
            throw "Failed to generate the local relay identity."
        }
        Protect-RelayIdentityFiles -IdentityPath $generationIdentityPath -SystemInstall:$SystemInstall
        $publicKey = Get-RelayPublicKeyFromIdentity -IdentityPath $generationIdentityPath

        if ($SystemInstall) {
            if ((Test-Path -LiteralPath $IdentityPath) -or (Test-Path -LiteralPath $publicKeyPath)) {
                throw "Relay identity appeared while a protected identity was being generated. Refusing to overwrite it."
            }
            Move-Item -LiteralPath $generationIdentityPath -Destination $IdentityPath
            Move-Item -LiteralPath "$generationIdentityPath.pub" -Destination $publicKeyPath
            Protect-RelayIdentityFiles -IdentityPath $IdentityPath -SystemInstall
            $publicKey = Get-RelayPublicKeyFromIdentity -IdentityPath $IdentityPath
        }
        $publicKey
    } finally {
        if ($generationRoot -and (Test-Path -LiteralPath $generationRoot)) {
            try {
                $generationParent = [IO.Path]::GetFullPath($PSScriptRoot).TrimEnd('\') + '\'
                $generationFullPath = [IO.Path]::GetFullPath($generationRoot)
                if (-not $generationFullPath.StartsWith($generationParent, [StringComparison]::OrdinalIgnoreCase)) {
                    throw "Refusing to clean an identity staging path outside the protected installer."
                }
                Assert-RelayTreeHasNoReparsePoints -Root $generationRoot
                Remove-Item -LiteralPath $generationRoot -Recurse -Force
            } catch {
                Write-Warning "A protected temporary identity directory could not be removed automatically."
            }
        }
    }
}

function Set-RelayEnrollmentConfiguration {
    param(
        [Parameter(Mandatory = $true)]$Pairing,
        [Parameter(Mandatory = $true)][string]$Root,
        [Parameter(Mandatory = $true)][string]$IdentityPath,
        [Parameter(Mandatory = $true)][string]$CreatedAtUtc
    )

    $schemaVersion = [int](Get-RequiredRelayProperty -Object $Pairing -Name "schema_version")
    if ($schemaVersion -ne 1) { throw "Unsupported pairing response version." }
    $remoteBind = [string](Get-RequiredRelayProperty -Object $Pairing -Name "remote_socks_bind")
    $remotePort = [int](Get-RequiredRelayProperty -Object $Pairing -Name "remote_socks_port")
    if ($remoteBind -ne "0.0.0.0" -or $remotePort -ne 1080) {
        throw "The server returned an unsafe or unsupported forwarding endpoint."
    }

    $knownHostsPath = Join-Path $Root "known_hosts"
    $config = [ordered]@{
        schemaVersion = 1
        relayId = [string](Get-RequiredRelayProperty -Object $Pairing -Name "relay_id")
        displayName = [string](Get-RequiredRelayProperty -Object $Pairing -Name "display_name")
        sshHost = [string](Get-RequiredRelayProperty -Object $Pairing -Name "ssh_host")
        sshPort = [int](Get-RequiredRelayProperty -Object $Pairing -Name "ssh_port")
        sshUser = [string](Get-RequiredRelayProperty -Object $Pairing -Name "ssh_user")
        remoteSocksBind = $remoteBind
        remoteSocksPort = $remotePort
        identityFile = $IdentityPath
        knownHostsFile = $knownHostsPath
        createdAtUtc = $CreatedAtUtc
        enrolledAtUtc = [DateTime]::UtcNow.ToString("o")
    }

    $hasPinnedHostKey = $Pairing.PSObject.Properties.Name -contains "host_key" -and $null -ne $Pairing.host_key
    $knownHostsTemporary = "$knownHostsPath.$PID.tmp"
    try {
        if ($hasPinnedHostKey) {
            $hostKeyType = [string](Get-RequiredRelayProperty -Object $Pairing.host_key -Name "type")
            $hostKeyData = [string](Get-RequiredRelayProperty -Object $Pairing.host_key -Name "data")
            if ($hostKeyType -notmatch '^ssh-(ed25519|rsa)$' -or $hostKeyData -notmatch '^[A-Za-z0-9+/]+={0,3}$') {
                throw "The server returned an invalid SSH host key."
            }
            $knownHostName = if ($config.sshPort -eq 22) { $config.sshHost } else { "[{0}]:{1}" -f $config.sshHost, $config.sshPort }
            Set-Content -LiteralPath $knownHostsTemporary -Value ("{0} {1} {2}" -f $knownHostName, $hostKeyType, $hostKeyData) -Encoding ASCII
        } else {
            New-Item -ItemType File -Path $knownHostsTemporary -Force | Out-Null
            Write-Warning "The pairing response did not include a host key. This enrollment will trust the first SSH key once, then pin it permanently."
        }
        Move-Item -LiteralPath $knownHostsTemporary -Destination $knownHostsPath -Force
    } finally {
        Remove-Item -LiteralPath $knownHostsTemporary -Force -ErrorAction SilentlyContinue
    }

    Write-RelayJsonAtomic -Path (Join-Path $Root "relay.json") -Value $config
    [pscustomobject]@{
        Config = Read-RelayConfig -InstallRoot $Root
        UseTrustOnFirstUse = -not $hasPinnedHostKey
    }
}

function Test-RelayEnrollment {
    param(
        [Parameter(Mandatory = $true)]$Config,
        [Parameter(Mandatory = $true)][string]$Root,
        [Parameter(Mandatory = $true)][bool]$UseTrustOnFirstUse
    )

    $sshPath = Get-RelaySshPath
    $errorPath = Join-Path (Join-Path $Root "logs") "enrollment-probe.err"
    Remove-Item -LiteralPath $errorPath -Force -ErrorAction SilentlyContinue
    $hostChecking = if ($UseTrustOnFirstUse) { "accept-new" } else { "yes" }
    $forward = "{0}:{1}" -f $Config.remoteSocksBind, [int]$Config.remoteSocksPort
    $target = "{0}@{1}" -f $Config.sshUser, $Config.sshHost
    $arguments = @(
        "-N", "-T", "-F", (Join-Path $Root "ssh_config"),
        "-i", [string]$Config.identityFile,
        "-p", [string]$Config.sshPort,
        "-o", "BatchMode=yes",
        "-o", "PasswordAuthentication=no",
        "-o", "KbdInteractiveAuthentication=no",
        "-o", "IdentitiesOnly=yes",
        "-o", ("StrictHostKeyChecking={0}" -f $hostChecking),
        "-o", ("UserKnownHostsFile={0}" -f $Config.knownHostsFile),
        "-o", "UpdateHostKeys=no",
        "-o", "ExitOnForwardFailure=yes",
        "-o", "ServerAliveInterval=10",
        "-o", "ServerAliveCountMax=2",
        "-o", "PermitLocalCommand=no",
        "-o", "LogLevel=ERROR",
        "-R", $forward,
        $target
    )
    $argumentLine = (($arguments | ForEach-Object { Quote-RelayProcessArgument -Value ([string]$_) }) -join " ")
    $process = Start-Process -FilePath $sshPath -ArgumentList $argumentLine -PassThru -WindowStyle Hidden -RedirectStandardError $errorPath
    try {
        if ($process.WaitForExit(4000)) {
            $reason = "SSH enrollment probe failed."
            if (Test-Path -LiteralPath $errorPath -PathType Leaf) {
                $message = Get-Content -LiteralPath $errorPath -Raw -ErrorAction SilentlyContinue
                if ($message) { $reason = ConvertTo-RelaySafeMessage -Message $message }
            }
            throw $reason
        }
    } finally {
        if (-not $process.HasExited) {
            Microsoft.PowerShell.Management\Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
        }
        Remove-Item -LiteralPath $errorPath -Force -ErrorAction SilentlyContinue
    }
}

function Stop-RelayProcessesForRoot {
    param([Parameter(Mandatory = $true)][string]$Root)

    # A manual installation is user-writable.  During an elevated migration we
    # must never execute, dot-source, delete, or write through files from that
    # tree.  Stopping only processes whose command line names the fixed relay
    # runtime/key paths is sufficient to release the reverse-forward port and
    # does not trust PID files or code from the old installation.
    $rootPath = [IO.Path]::GetFullPath($Root).TrimEnd('\')
    $relayFragment = Join-Path $rootPath "Relay.ps1"
    $identityFragment = Join-Path $rootPath "relay_ed25519"
    $candidates = CimCmdlets\Get-CimInstance Win32_Process -ErrorAction SilentlyContinue
    foreach ($candidate in $candidates) {
        $name = [string]$candidate.Name
        $commandLine = [string]$candidate.CommandLine
        if (-not $commandLine) { continue }
        $isRelayRunner = $name -in @("powershell.exe", "pwsh.exe") -and $commandLine.IndexOf($relayFragment, [StringComparison]::OrdinalIgnoreCase) -ge 0
        $isRelaySsh = $name -eq "ssh.exe" -and $commandLine.IndexOf($identityFragment, [StringComparison]::OrdinalIgnoreCase) -ge 0
        if ($isRelayRunner -or $isRelaySsh) {
            Microsoft.PowerShell.Management\Stop-Process -Id ([int]$candidate.ProcessId) -Force -ErrorAction SilentlyContinue
        }
    }
}

Assert-RelayWindows
if ($EnableAutoStart -and $DisableAutoStart) {
    throw "Choose either EnableAutoStart or DisableAutoStart, not both."
}
$localInstallRoot = Get-DefaultRelayRoot
$systemInstallRoot = Join-Path (Get-RelayProgramDataPath) "FunPayHomeRelay"
if ([string]::IsNullOrWhiteSpace($InstallRoot)) {
    if ($EnableAutoStart -or (Test-Path -LiteralPath (Join-Path $systemInstallRoot "relay.json") -PathType Leaf)) {
        $InstallRoot = $systemInstallRoot
    } else {
        $InstallRoot = $localInstallRoot
    }
}
$isSystemInstall = Test-RelaySystemInstallRoot -Path $InstallRoot
if (-not $isSystemInstall -and -not (Test-RelayManualInstallRoot -Path $InstallRoot)) {
    throw "InstallRoot must be the canonical LocalAppData manual path or the protected ProgramData boot path."
}
if ($EnableAutoStart -and -not $isSystemInstall) {
    throw "EnableAutoStart requires the canonical protected ProgramData installation path."
}
$existingAutoTask = ScheduledTasks\Get-ScheduledTask -TaskName $script:RelayTaskName -ErrorAction SilentlyContinue
$openSshRoot = Join-Path (Get-RelayWindowsPath) "System32\OpenSSH"
$openSshMissing = (
    -not (Test-Path -LiteralPath (Join-Path $openSshRoot "ssh.exe") -PathType Leaf) -or
    -not (Test-Path -LiteralPath (Join-Path $openSshRoot "ssh-keygen.exe") -PathType Leaf)
)
$isAdministrator = Test-RelayAdministrator
$isManualUserInstall = -not $isSystemInstall -and -not $EnableAutoStart

# Never execute a LocalAppData runtime with a high-integrity token.  If the
# built-in OpenSSH capability is missing, the elevated pass installs only that
# Windows component and exits before reading/consuming the pairing code or
# creating user-writable runtime files.  The same command is then run once in a
# normal PowerShell window to perform enrollment.
if ($isManualUserInstall -and $isAdministrator) {
    if ($openSshMissing) {
        Install-RelayOpenSshIfNeeded
        Write-Host "OpenSSH Client is installed. Close this Administrator window and run the same setup command in a normal PowerShell window. The one-time pairing code was not consumed."
        exit 0
    }
    throw "Manual mode must run in a normal, non-administrator PowerShell window. Use autostart mode for a protected system installation."
}
$needsElevation = $isSystemInstall -or $EnableAutoStart -or $openSshMissing -or ($DisableAutoStart -and $null -ne $existingAutoTask)
if ($needsElevation -and -not $isAdministrator) {
    throw "Administrator rights are required for boot autostart, a protected system-install repair, or OpenSSH installation. For safety, this downloaded installer will not self-elevate from a user-writable directory. Open PowerShell using 'Run as administrator' and paste the generated setup command again."
}
if ([string]::IsNullOrWhiteSpace($DisplayName) -or $DisplayName.Length -gt 80) {
    throw "DisplayName must contain 1 to 80 characters."
}
Install-RelayOpenSshIfNeeded

$configPath = Join-Path $InstallRoot "relay.json"
if ($isSystemInstall -and (Test-Path -LiteralPath $InstallRoot)) {
    Repair-RelaySystemPublicKeyProtection -Root $InstallRoot
    Assert-RelayProtectedSystemRuntime -Root $InstallRoot
}
$migratingFromLocal = (
    $EnableAutoStart -and
    $isSystemInstall -and
    -not (Test-Path -LiteralPath $configPath -PathType Leaf) -and
    (Test-Path -LiteralPath $localInstallRoot -PathType Container)
)
if ($migratingFromLocal) {
    Write-Host "Stopping the existing manual relay before enabling secure boot mode."
    Stop-RelayProcessesForRoot -Root $localInstallRoot
}
if (Test-Path -LiteralPath $configPath -PathType Leaf) {
    Write-Host "Existing installation found. Refreshing runtime files without rotating its identity."
    if ($isSystemInstall) {
        Assert-RelayProtectedSystemRuntime -Root $InstallRoot
    }
    Protect-RelayDirectory -Path $InstallRoot -SystemInstall:$isSystemInstall
    Copy-RelayRuntimeFiles -Destination $InstallRoot
    $existingConfig = Read-RelayConfig -InstallRoot $InstallRoot
    if ($isSystemInstall) {
        Assert-RelayProtectedPath -Path ([string]$existingConfig.identityFile)
        Assert-RelayProtectedPath -Path ([string]$existingConfig.knownHostsFile)
    }
    Protect-RelayIdentityFiles -IdentityPath ([string]$existingConfig.identityFile) -SystemInstall:$isSystemInstall
    $reEnrollRequested = -not [string]::IsNullOrWhiteSpace($PairingUrl) -or -not [string]::IsNullOrWhiteSpace($PairingCode)
    if ($reEnrollRequested) {
        if ([string]::IsNullOrWhiteSpace($PairingUrl)) {
            throw "PairingUrl is required when a new PairingCode is supplied."
        }
        $plainCode = Get-PlainPairingCode -Code $PairingCode
        if ([string]::IsNullOrWhiteSpace($plainCode)) {
            throw "The pairing code is empty."
        }

        Write-Host "Re-enrolling the existing local relay identity with the new one-time setup."
        & (Join-Path $InstallRoot "Stop.ps1") -InstallRoot $InstallRoot
        $oldConfigBytes = [IO.File]::ReadAllBytes($configPath)
        $oldKnownHostsPath = [string]$existingConfig.knownHostsFile
        $oldKnownHostsBytes = [IO.File]::ReadAllBytes($oldKnownHostsPath)
        try {
            $existingPublicKey = Get-RelayPublicKeyFromIdentity -IdentityPath ([string]$existingConfig.identityFile)
            try {
                $pairing = Invoke-RelayPairing -Url $PairingUrl -Code $plainCode -PublicKey $existingPublicKey -Name $DisplayName
            } finally {
                $plainCode = $null
                $PairingCode = $null
            }
            $createdAtUtc = if ($existingConfig.PSObject.Properties.Name -contains "createdAtUtc") { [string]$existingConfig.createdAtUtc } else { [DateTime]::UtcNow.ToString("o") }
            $enrollment = Set-RelayEnrollmentConfiguration -Pairing $pairing -Root $InstallRoot -IdentityPath ([string]$existingConfig.identityFile) -CreatedAtUtc $createdAtUtc
            Protect-RelayDirectory -Path $InstallRoot -SystemInstall:$isSystemInstall
            Protect-RelayIdentityFiles -IdentityPath ([string]$existingConfig.identityFile) -SystemInstall:$isSystemInstall
            Test-RelayEnrollment -Config $enrollment.Config -Root $InstallRoot -UseTrustOnFirstUse:$enrollment.UseTrustOnFirstUse
            $existingConfig = $enrollment.Config
            Write-Host "Existing relay identity re-enrolled and its SSH host key refreshed."
        } catch {
            [IO.File]::WriteAllBytes($configPath, $oldConfigBytes)
            [IO.File]::WriteAllBytes($oldKnownHostsPath, $oldKnownHostsBytes)
            Protect-RelayDirectory -Path $InstallRoot -SystemInstall:$isSystemInstall
            Protect-RelayIdentityFiles -IdentityPath ([string]$existingConfig.identityFile) -SystemInstall:$isSystemInstall
            try { & (Join-Path $InstallRoot "Start.ps1") -InstallRoot $InstallRoot } catch { }
            throw
        }
    }
    if ($EnableAutoStart) {
        & (Join-Path $InstallRoot "Stop.ps1") -InstallRoot $InstallRoot
        Register-RelayAutoStart -Root $InstallRoot
    }
    if ($DisableAutoStart) { Remove-RelayAutoStart }
    Install-RelayShortcuts -Root $InstallRoot -SystemInstall:$isSystemInstall -Desktop:$CreateDesktopShortcuts
    & (Join-Path $InstallRoot "Start.ps1") -InstallRoot $InstallRoot
    exit 0
}

if (-not $PairingUrl) {
    throw "PairingUrl is required for the first installation."
}
$plainCode = Get-PlainPairingCode -Code $PairingCode
if ([string]::IsNullOrWhiteSpace($plainCode)) {
    throw "The pairing code is empty."
}

Initialize-RelayDirectory -Path $InstallRoot -SystemInstall:$isSystemInstall
New-Item -ItemType Directory -Path (Join-Path $InstallRoot "logs") -Force | Out-Null
Copy-RelayRuntimeFiles -Destination $InstallRoot

$identityPath = Join-Path $InstallRoot "relay_ed25519"
$publicKey = Get-OrCreateRelayIdentity -Root $InstallRoot -IdentityPath $identityPath -SystemInstall:$isSystemInstall
try {
    $pairing = Invoke-RelayPairing -Url $PairingUrl -Code $plainCode -PublicKey $publicKey -Name $DisplayName
} finally {
    $plainCode = $null
    $PairingCode = $null
}

$createdAtUtc = [DateTime]::UtcNow.ToString("o")
$enrollment = Set-RelayEnrollmentConfiguration -Pairing $pairing -Root $InstallRoot -IdentityPath $identityPath -CreatedAtUtc $createdAtUtc
Protect-RelayDirectory -Path $InstallRoot -SystemInstall:$isSystemInstall
Protect-RelayIdentityFiles -IdentityPath $identityPath -SystemInstall:$isSystemInstall
Test-RelayEnrollment -Config $enrollment.Config -Root $InstallRoot -UseTrustOnFirstUse:$enrollment.UseTrustOnFirstUse

if ($EnableAutoStart) { Register-RelayAutoStart -Root $InstallRoot }
if ($DisableAutoStart) { Remove-RelayAutoStart }
Install-RelayShortcuts -Root $InstallRoot -SystemInstall:$isSystemInstall -Desktop:$CreateDesktopShortcuts
& (Join-Path $InstallRoot "Start.ps1") -InstallRoot $InstallRoot
if ($migratingFromLocal -and (Test-Path -LiteralPath $localInstallRoot)) {
    Write-Host "The previous manual installation was left in place as an inert backup. Delete it later from a normal PowerShell window after confirming boot mode works."
}

Write-Host ""
Write-Host "FunPay Home Relay installed in $InstallRoot"
Write-Host "The private key remains on this Windows machine. The one-time pairing code was not saved."
if ($EnableAutoStart) {
    Write-Host "Autostart is enabled at Windows boot. Keep this PC awake while account checks run."
} else {
    Write-Host "Autostart is disabled. Use the Start shortcut when the relay is needed."
}
